### ISSUE TITLE
looking for yolo-fastest-1.1_160_person_himax.weight

### ISSUE THREAD

**Issue by JJunHan** [HimaxWiseEyePlus/Yolo-Fastest#2]
Is the yolo-fastest-1.1_160_person_himax.weight file released? I would like to use hi-max trained model as a pretrained model but cant find it under "/modelzoo". Thanks.

**Comment by kris-himax** [comment]
@JJunHan hi
It is at the below link. It is the model which we train by the person images captured at our HIMAX office.
https://github.com/HimaxWiseEyePlus/Yolo-Fastest/blob/master/ModelZoo/yolo-fastest-1.1_160_person/yolo-fastest-1_1_160_person_himax.tflite

**Comment by JJunHan** [comment]
@kris-himax hi kris, that link is for the converted .tflite file, but I was looking for the .weights file to generate a pre-trained model (using darknet) to re-train with other datasets.

**Comment by kris-himax** [comment]
@JJunHan hi
We provide the .weights file at below link.
https://github.com/HimaxWiseEyePlus/Yolo-Fastest/blob/master/ModelZoo/yolo-fastest-1.1_160_person/yolo-fastest-1_1_160_person_himax.weights
